# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('body_html', models.CharField(max_length=1023)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('variants', jsonfield.fields.JSONField(default=dict)),
                ('options', jsonfield.fields.JSONField(default=dict)),
                ('images', jsonfield.fields.JSONField(default=dict)),
                ('image', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
