# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
