# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-10 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170910_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
